JNG-4803 Deleting as a parent type
BlackBeltTechnology/judo-runtime-core pull request #131
Opened 2023-05-04 11:43 UTC by bencegelei

2023-05-04 13:30 UTC, robertcsakany requested changes

2023-05-04 13:30 UTC, robertcsakany commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/executors/DeleteStatementExecutor.java
> +                                checkState(count == 0 || count == 1, "Maximum of 1 record should have been deleted. Actual: " + count);
When zero record is presented, the message lies.

2023-05-04 13:30 UTC, robertcsakany commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/executors/DeleteStatementExecutor.java
> +                    types.add(entity);
Maybe better if AsmUtil have method where descandences can be query for an EClass. This recursive superclass collection for every class can be time consuming on every delete operation.

2023-05-04 13:30 UTC, robertcsakany commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/executors/DeleteStatementExecutor.java
> +                    types.add(entity);
And isEntityType check is missing.

2023-05-04 14:09 UTC, bencegelei commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/executors/DeleteStatementExecutor.java
> +                                checkState(count == 0 || count == 1, "Maximum of 1 record should have been deleted. Actual: " + count);
If no records were affected, there is no message.

2023-05-04 14:56 UTC, noherczeg approved these changes

2023-05-04 17:51 UTC, robertcsakany approved these changes

2023-05-05 07:38 UTC, gaborflorian approved these changes

2023-05-05 08:37 UTC, merged