bugfix/JNG-3900-fix-time-asstring
BlackBeltTechnology/judo-runtime-core pull request #56
Opened 2022-10-17 12:48 UTC by noherczeg

2022-10-17 14:10 UTC, bencegelei requested changes
~~Related part should be commented in Postgresql mapper~~
Postgresql produces acceptable string value the current way

2022-10-19 11:16 UTC, bencegelei approved these changes

2022-10-24 07:56 UTC, robertcsakany approved these changes

2022-10-24 08:41 UTC, gaborflorian approved these changes

2022-10-24 09:56 UTC, merged