JNG-4225 When model name is not defined trying to search model on cla…
BlackBeltTechnology/judo-runtime-core pull request #94
Opened 2022-12-23 14:14 UTC by robertcsakany

…sspath

2022-12-23 14:59 UTC, noherczeg requested changes

2022-12-23 14:59 UTC, noherczeg commented on judo-runtime-core-spring/src/main/java/hu/blackbelt/judo/runtime/core/spring/JudoModelLoaderConfiguration.java
> +            throw new IllegalArgumentException("modelName is not set and could not determinate");
"Could not be determined"

2022-12-23 15:28 UTC, noherczeg approved these changes

2022-12-28 09:09 UTC, noherczeg approved these changes

2023-01-02 14:41 UTC, gaborflorian approved these changes

2023-01-02 14:46 UTC, merged