JNG-4184 Static navigation causes SQL exception in derived attribute
BlackBeltTechnology/judo-runtime-core pull request #95
Opened 2023-01-18 15:47 UTC by bencegelei

2023-01-18 17:36 UTC, robertcsakany requested changes

2023-01-18 17:36 UTC, robertcsakany commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/query/model/RdbmsResultSet.java
> +        final RdbmsJoin firstJoin = !joins.isEmpty() ? joins.get(0) : null;
Is there any reason that firstJoin inisialization is moved here? As I see this change doesn't change in the behaviour, so unneccessary.

2023-01-18 17:39 UTC, noherczeg approved these changes

2023-01-19 07:27 UTC, robertcsakany approved these changes

2023-01-24 10:12 UTC, robertcsakany approved these changes

2023-01-24 11:05 UTC, merged