JNG-4342 Invalid sql select with derived aggregation
BlackBeltTechnology/judo-runtime-core pull request #99
Opened 2023-02-02 14:07 UTC by bencegelei

JNG-4342 Invalid sql select with derived aggregation

2023-02-08 16:49 UTC, robertcsakany approved these changes

2023-02-08 16:54 UTC, noherczeg requested changes
Please revert formatting changes. PR is too noisy.

2023-02-08 17:01 UTC, bencegelei commented
> 409c013

[409c013](https://github.com/BlackBeltTechnology/judo-runtime-core/pull/99/commits/409c0132fc319594ba6c5f285453cf1e63f97ec8)

2023-02-08 17:02 UTC, noherczeg approved these changes

2023-02-09 07:57 UTC, Madmat8 approved these changes

2023-02-09 11:29 UTC, gaborflorian approved these changes

2023-02-09 13:28 UTC, fmagnucz approved these changes

2023-02-09 13:28 UTC, fmagnucz commented on judo-runtime-core-dao-rdbms/src/main/java/hu/blackbelt/judo/runtime/core/dao/rdbms/query/RdbmsBuilder.java
> +            Node partnerTable = ((CastJoin) join).getPartner();
`String alias = join.getAlias();
 Node partnerTable = ((CastJoin) join).getPartner();`
Put before the for loop.

2023-02-09 13:47 UTC, merged